name: Node.js CI

on:
  release:
      types: [created]
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release'

    steps:
    - name: checkout
      uses: actions/checkout@v4.1.2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@aegenet'
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Install dependencies
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: rm -rf node_modules && npm i
    - name: build
      run: npm run build build
    - name: lint
      run: npm run lint
    - name: test and coverage
      run: npm run test:coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.3.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        slug: aegenet/yawt

    - name: Publish packages GitHub
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_AUTH_TOKEN }}
        YAWT_NPM_PUBLIC_PUBLISH: 'false'
        YAWT_NPM_PUSH_REGISTRY: https://npm.pkg.github.com/
        YAWT_NPM_NAMESPACE: '@aegenet'
      run: node ./dist/yawt-cli.cjs --task="publish" --single
    - name: Publish packages npm
      if: github.event_name == 'release'
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        YAWT_NPM_PUBLIC_PUBLISH: 'true'
        YAWT_NPM_PUSH_REGISTRY: https://registry.npmjs.org/
        YAWT_NPM_NAMESPACE: '@aegenet'
      run: node ./dist/yawt-cli.cjs --task="publish" --single

  # Pull Request
  build_pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'

    steps:
    - name: checkout
      uses: actions/checkout@v4.1.2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@aegenet'
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Install dependencies
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN  }}
      run: rm -rf node_modules && npm i
    - name: build
      run: npm run build
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test